### ISSUE TITLE
Hovering Arrow

### ISSUE THREAD

**Issue by sdv3** [micahswitzer/ShowMe#1]
It would be convenient, if hovering the tool over an entity would show the players a big arrow over that entity. So that I don't have to constantly draw a frame to show my teammates what I am talking about.
That arrow could also show some entity info near it (ex, logical setup)

**Comment by micahswitzer** [comment]
Hey @sdv3 I totally agree that this would be an awesome feature! Could you possibly provide more detail as to what you'd like to see in the "entity info" you mentioned?

**Comment by micahswitzer** [comment]
Hey @sdv3 I've implemented this basic feature in version 0.1.6, but I'm still curious as to what you mean by "entity info"

**Comment by micahswitzer** [comment]
Closing, because the OP [seemed satisfied with the changes](https://mods.factorio.com/mod/ShowMe/discussion/5e522a35461111000bffebbd).
